04-SPA/[ 03-NotFound, 04-Layouts, 05-AuthPages ]
js-tasks-ru/vue-20201210_aleksandr822 pull request #10
Opened 2021-01-05 14:29 UTC by PIPSKVIK

2021-01-05 14:55 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
LoginPage и RegisterPage
+ LoginPage должен выводить "Требуется ввести Email" при сабмите без введённого email
+ LoginPage должен выводить "Требуется ввести пароль" при сабмите c email, но без введённого пароля
+ LoginPage должен выводить "Неверные учетные данные" при сабмите с неверными данными
+ LoginPage должен выводить полное имя при сабмите с верными данными
+ RegisterPage должен выводить "Требуется ввести Email" при сабмите без введённого email
+ RegisterPage должен выводить "Требуется ввести полное имя" при сабмите без полного имени
+ RegisterPage должен выводить "Требуется ввести пароль" при сабмите без пароля
+ RegisterPage должен выводить "Пароли не совпадают" при сабмите с несовпадающими паролями
+ RegisterPage должен выводить "Требуется согласиться с условиями" при сабмите без согласия
+ RegisterPage должен выводить ошибку при неуспешной регистрации
+ RegisterPage должен выводить ID пользователя при успешной регистрации
+ LoginPage должен рендериться на странице /login
+ RegisterPage должен рендериться на странице /register
```
```diff
Layouts
+ TheHeader не должен быть пустым
+ TheFooter не должен быть пустым
+ BaseLayout не должен быть пустым
+ FormLayout не должен быть пустым
+ AuthLayout не должен быть пустым
```
```diff
404 - NotFound
+ NotFoundPage должен отображаться, когда страница не найдена
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2021-01-06 18:34 UTC, ShGKme requested changes
Требуются исправления в задаче `Layouts`, остальные задачи приняты.

2021-01-06 18:34 UTC, ShGKme commented on 04-SPA/04-Layouts/components/AuthLayout.vue
> +        </form>
`Layout` - это некоторый шаблон с общими частями для разных страниц. `AuthLayout` - это маленький компонент, который содержит общие части для страниц входа и регистрации: блок с определёнными классами и заголовком. Сама форма может быть разной в зависимости от конкретной страницы. На странице входа одна форма, а на странице регистрации - другая.

Здесь, также как на `BaseLayout`, должен быть слот, куда будет передаваться содержимое страницы.

`FormLayout` - аналогично.

2021-01-07 10:25 UTC, PIPSKVIK commented on 04-SPA/04-Layouts/components/AuthLayout.vue
> +        </form>
Григорий, добрый день!
Я надеюсь правильно понял Ваш комментарий, добавил изменения.

2021-01-07 10:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-01-11 13:50 UTC, ShGKme requested changes
Требуются ещё небольшие изменения в задаче `Layouts`: не хватает стилей.

2021-01-11 13:50 UTC, ShGKme commented on 04-SPA/04-Layouts/views/LoginPage.vue
>  </template>
Редактировать файлы вне списка файлов задачи из инструкции в условии не требуется. Данный компонент - просто пример, заглушка для ручного тестирования.

Редактировать, конечно, можно, но для удобства, для тестирования, для экспериментов и т.д.

2021-01-11 13:50 UTC, ShGKme commented on 04-SPA/04-Layouts/components/FormLayout.vue
Не хватает стилей:
https://github.com/js-tasks-ru/vue-course-materials/blob/master/meetups-markup/styles/_page_forms.css

2021-01-11 13:50 UTC, ShGKme commented on 04-SPA/04-Layouts/components/AuthLayout.vue
> +</style>
Не хватает стилей:
https://github.com/js-tasks-ru/vue-course-materials/blob/master/meetups-markup/styles/_page_onboarding.css

2021-01-12 07:19 UTC, PIPSKVIK commented on 04-SPA/04-Layouts/components/AuthLayout.vue
> +</style>
Стили я добавил.

2021-01-12 07:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-01-12 16:16 UTC, ShGKme requested changes
Ещё чуть-чуть

2021-01-12 16:16 UTC, ShGKme commented on 04-SPA/04-Layouts/components/FormLayout.vue
> +  </div>
Чуть-чуть не хватает (блока, для которого добавлены стили).
https://github.com/js-tasks-ru/vue-course-materials/blob/master/meetups-markup/meetup-form.html#L29

2021-01-12 16:16 UTC, ShGKme commented on 04-SPA/04-Layouts/components/AuthLayout.vue
> +  <main class="main">
`<main>` у вас уже есть в `BaseLayout`...

2021-01-13 05:07 UTC, PIPSKVIK commented
Григорий добрый день, тут последние правки по 04-SPA\04-Layouts.
И еще две задачи по 06-deep-vue

2021-01-13 05:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-01-13 12:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-01-14 00:10 UTC, ShGKme approved these changes
Все задачи приняты 🎉

2021-01-14 00:10 UTC, ShGKme commented on 06-deep-vue/01-Buttons/components/DangerButton.vue
> +  nheritAttrs: false,
`inherit`*.
Но в этих компонентах эта настройка не требуется, так как кнопка итак является корневым элементом.

Наследование атрибутов требуется отключать тогда, когда корневым элементом является тот, на которому не нужно наследовать атрибуты. 

В примере на вебинаре у нас был `input` в обёртке из `div`. Именно `div` был тем корневым элементом, который должен был быть без унаследованных атрибутов.

2021-01-14 00:10 UTC, ShGKme commented on 06-deep-vue/05-nextTick/components/MiniMessenger.vue
> +        this.$refs['messages'].$el.scrollTop = this.$refs['messages'].$el.scrollHeight
Более точное решение - `scrollHeight - clientHeight`

2021-01-14 00:12 UTC, merged