add solution for 06-deep-vue\06-Transition-1
js-tasks-ru/vue-20201210_aleksandr822 pull request #11
Opened 2021-01-15 14:15 UTC by PIPSKVIK

Григорий, добрый день.

Я так понимаю сделал какую-то ерунду.
Но я не понимаю как дальше быть.
Что применять.
Или тут нужно как-то расписывать Хуки для анимации.
Оно вроде работает, но как-то странно.

Я пробовал делать в песочнице несколько вариантов из документации, все получаться понятно, а тут не понимаю.
Можно ли трогать слили или нет.

Прошу немного подсказать =)

2021-01-15 14:27 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Transitions-1
+ FadeTransition добавлен, но требует ручной проверки
+ FadeTransitionGroup добавлен, но требует ручной проверки
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2021-01-17 14:16 UTC, PIPSKVIK commented
Григорий, добрый день.
У меня проблема с 06-deep-vue\02-AppInput.
Не пойму как быть с иконками, вроде делаю как в примере.

2021-01-17 14:19 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
AppInput
+ AppInput должен иметь параметры small, rounded и multiline
+ AppInput должен рендерить поле ввода с классом form-control внутри блока input-group
+ AppInput должен иметь класс form-control_sm только с параметром small
+ AppInput должен иметь класс form-control_rounded только с параметром rounded
+ AppInput с параметром multiline должен рендерить многострочное поле ввода
+ Параметры small и rounded должны работать с многострочным AppInput
+ AppInput должен принимать различные атрибуты полей ввода
+ AppInput должен принимать различные атрибуты полей ввода для textarea
+ AppInput должен рендерить input type=(password)
+ AppInput должен рендерить input type=(num)
+ AppInput должен рендерить input type=(range)
+ AppInput должен рендерить input type=(date)
+ AppInput должен рендерить input type=(time)
+ AppInput должен рендерить input type=(email)
+ AppInput должен рендерить input type=(tel)
+ AppInput должен выводить текущее значение (multiline=false)
+ AppInput должен выводить текущее значение (multiline=true)
+ AppInput должен обрабатывать нативный ввод и порождать события input, change с введённым значением
- AppInput должен выводить левую иконку и добавлять классы input-group_icon input-group_icon-left
- AppInput должен выводить правую иконку и добавлять классы input-group_icon input-group_icon-right
```
```diff
Transitions-1
+ FadeTransition добавлен, но требует ручной проверки
+ FadeTransitionGroup добавлен, но требует ручной проверки
```

2021-01-21 09:55 UTC, ShGKme commented on 06-deep-vue/02-AppInput/components/AppInput.vue
>      <img class="icon" />
У вас нет слотов, куда можно передать иконку. Т.е. в компоненте выводятся фиксированные картинки всегда, не зависимо от того, какое изображение (иконка) передано в какой из слотов.

2021-01-21 09:55 UTC, ShGKme commented on 06-deep-vue/02-AppInput/components/AppInput.vue
> +    },
Слоты не реактивные, и недостаточно использовать простые вычисляемые свойства
https://vuejs.org/v2/api/#vm-slots

2021-01-22 06:42 UTC, PIPSKVIK commented on 06-deep-vue/02-AppInput/components/AppInput.vue
>      <img class="icon" />
Даа, что-то не обратил внимание что в App компоненте они хотят name slot))

2021-01-22 08:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-01-22 09:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-01-22 21:02 UTC, ShGKme requested changes
Требуется небольшое изменение в задаче `Transitions-1`

2021-01-22 21:02 UTC, ShGKme commented on 06-deep-vue/06-Transitions-1/components/FadeTransition.vue
> +  <div>
Элемент `div` здесь не нужен. При этом не передачи параметров и обработчиков событий на `<transition>`, аналогично предыдущим задачам, где требуется обёртка над каким-то компонентом.

2021-01-22 21:02 UTC, ShGKme commented on 06-deep-vue/06-Transitions-1/components/FadeTransitionGroup.vue
> +    <transition-group name="fade">
Аналогично, требуется передавать переданные обработчики событий и параметры, чтобы сделать полноценную обёртку над компонентом.

Это позволит в будущем использовать компонент для разных задач, и создавать поверх ещё обёртки при необходимости.

2021-01-27 10:56 UTC, ShGKme approved these changes
Все задачи приняты 👍

2021-01-27 10:56 UTC, ShGKme commented on 06-deep-vue/06-Transitions-1/components/FadeTransition.vue
> +  inheritAttrs: false,
`inheritAttrs: false` нужен, когда требуется не передавать атрибуты на корневой элемент, либо они передаются на некоторый внутренний элемент (как было в `AppInput`, где корневым был просто `div`). Здесь же нужный элемент уже является корневым, и необходимости отключать наследование атрибутов - нет.

2021-01-27 10:57 UTC, merged