add solution for 02-MeetupPageDraft
js-tasks-ru/vue-20201210_aleksandr822 pull request #2
Opened 2020-12-16 19:16 UTC by PIPSKVIK

Задача  - Meetup Page Draft

2020-12-16 21:10 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Meetup Page Draft
+ Задача добавлена, но требует ручной проверки
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2020-12-17 00:01 UTC, ShGKme requested changes
Требуется установить в качестве начального значения данных митапа null, избавиться от вызова метода в шаблоне и добавить проверку на отсутствие изображения в изображение митапа.

2020-12-17 00:01 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/MeetupAgenta.js
> +      <p class="meetup-agenda__empty">Программа пока пуста, но когда-нибудь в ней обязательно что-нибудь появится!</p>
Кажется, это сообщение не должно выводиться всегда...

2020-12-17 00:01 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/MeetupAgenta.js
> +      <meetup-agenta-item v-for="(items, id) in agenta" :key="id" :item="items"/>
Мы узнаем об этом позже, но использование индекса в качестве ключа списка - бесполезно, так как порядковый номер не идентифицирует элемент списка

2020-12-17 00:01 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/index.html
> +              <time datetime="2020-02-31">{{ localdate(meetupItem.date) }}</time>
Лучше избегать вызова методов в шаблоне.
Здесь может быть простое выражение, либо свойство, либо вычисляемое свойство.

Метод - как обычная функция, будет вызываться каждый раз, когда будет происходить ререндеринг (когда vue встретит вызов метода в шаблоне). Вычисляемые свойства же будут перевычисляться  только тогда, когда изменяются свойства, от которых они зависят. Другими словами можно сказать, что computed - кэшируется.

Хотя здесь метод очень простой и не затратный, в начале важно научитсья работать с вычисляемыми свойствами

2020-12-17 00:01 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/index.html
> +    <div class="meetup-cover" :style="`--bg-url: url('${meetupBackgrounById}')`">
Если изображение будет отсутствовать, то такой стиль собьёт изоражение по умолчанию...
Требуется, если изображения нет, не добавлять никаких стилей

2020-12-17 00:01 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/script.js
> +      meetupItem: []
Устанавливать начальным значением объекта с данными митапа список - не очень корректно. Это не список и не будет списком.
Лучше, пока данных нет, иметь значение `null` и добавить проверки как в вычисляемое свойство, так и в шаблон, чтобы не выводить страницу, пока данных нет (добавить где-то наверху v-if).

Хотя установка начального значения в [] избавляет от простых ошибок, она не избавляет от ошибок полностью, оставляя более трудно-находимые ошибки. Лучше начальным значением указать null и делать проверки. Например, сейчас на время загрузки митапа отображается "сломанная" страница с пустыми значениями.

2020-12-17 13:42 UTC, PIPSKVIK commented on 01-basics/02-MeetupPageDraft/MeetupAgenta.js
> +      <meetup-agenta-item v-for="(items, id) in agenta" :key="id" :item="items"/>
Да, я тоже слышал, тогда в данном случае у каждого элемента items есть свой id.
И к нему буду стучатся, так как консоль предупреждает)
`:key="items.id"`

2020-12-17 14:08 UTC, PIPSKVIK commented on 01-basics/02-MeetupPageDraft/index.html
> +    <div class="meetup-cover" :style="`--bg-url: url('${meetupBackgrounById}')`">
Я так понимаю, вот такая проверка поможет?
`return getMeetupCoverLink(this.meetupItem) ? getMeetupCoverLink(this.meetupItem) : undefined;`

2020-12-17 15:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2020-12-17 16:18 UTC, ShGKme approved these changes
Принято 👍

2020-12-17 16:19 UTC, merged